### ISSUE TITLE
No active of 2FA is possible

### ISSUE THREAD

**Issue by Cretection** [codeFareith/cf_google_authenticator#1]
After install the Extension:

It is not possible to edit a user in "Backend User"-Modul anymore.
-> "Oops, an error occurred! Neither the 'issuer' parameter nor the 'accountName' parameter may contain a colon."

So the Manual stop's at open user and no active of 2FA is possible.

System requirements:

TYPO3 8.7.16 (no composer)
PHP 7.1

**Comment by codeFareith** [comment]
Hi Jonathan,

could you please check the following:
1. in the TYPO3 CMS backend navigate to **configuration**, select **$GLOBALS[TYPO3_CONF_VARS]** from the dropdown, expand **SYS** and search for **sitename**. What's its value? Does it contain a colon ( : ) ?
2. check your TYPO3 CMS backend username. Does it contain a colon?

As the error message sais: neither *issuer* (= sitename) nor *accountName* (= username) should contain a colon.
