### ISSUE TITLE
Please publish to packagist

### ISSUE THREAD

**Issue by xperseguers** [codeFareith/cf_google_authenticator#11]
According to `composer.json`, this extension should be available off packagist under https://packagist.org/packages/codefareith/cf-google-authenticator

Since this is not published there, it is not possible to install it "easily" with a composer-based TYPO3 installation.

**Comment by xperseguers** [comment]
Just as a follow-up, to make it crystal clear.

Current way of using it with composer is adding a dependency like that:

```
"typo3-ter/cf-google-authenticator": "^1.1.2"
````

whereas it should logically be:

```
"codefareith/cf-google-authenticator": "^1.1.2"
```

instead since using `typo3-ter` is just available for convenience when developer did not (yet) publish to Packagist as he should.

**Comment by codeFareith** [comment]
You're right, I'll publish it soon. Thank you

**Comment by codeFareith** [comment]
The extension is now published to packagist.
But I'll keep the ticket open 'til I've setup the hook.

**Comment by codeFareith** [comment]
Done
