### ISSUE TITLE
FE SetupController: class import for Context missing

### ISSUE THREAD

**Issue by stoppeye** [codeFareith/cf_google_authenticator#144]
# Bug report

## Prerequisites
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Description:
Trying to open the page with the "Google Two-Factor-Authentication Setup" plugin throws an error

## Steps to reproduce:
1. open setup page
2. See error

## Expected results:
Setup page opens

## Actual results:
Error message (shortened): ... must be an instance of CodeFareith\CfGoogleAuthenticator\Controller\Frontend\Context, instance of TYPO3\CMS\Core\Context\Context given ...

## Notes:
Adding ```use TYPO3\CMS\Core\Context\Context;```fixes the problem

**Comment by codeFareith** [comment]
Thank you very much for the hint, I will take care of the problem as soon as possible.
Could you please tell me which version of TYPO3 you are using?

**Comment by stoppeye** [comment]
TYPO3 9 LTS (9.5.18)

**Comment by codeFareith** [comment]
This bug should be fixed in current version 1.2.0. Please verify 😊

**Comment by stoppeye** [comment]
Yeah, that seems to wirk fine now. Thanks for fixing it so quickly!

There are still some issues with translations however. But I'll open a new issue for that.
