### ISSUE TITLE
Inconsistent (or missing) translations

### ISSUE THREAD

**Issue by stoppeye** [codeFareith/cf_google_authenticator#145]
# Bug report

## Prerequisites
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version

## Description:
1. The German FE translations (de.locallang.xlf) are basically missing.
2. The button text for the enable/disable buttons is hardcoded in the FE template (Templates/Frontend/Setup/Index.html)
3. Flash messages in wrong language

## Steps to reproduce:
1. Run extension in a German FE

## Expected results:
German translation applied consistently

## Actual results:
Missing or wrong translations

## Notes:
For our project I have created German translations myself. I can provide those files if you want.
BTW: I think the wording is not very consistent, ie. sometimes the term "one-time password" is used, while other times it's called "verification code"; I think this can be confusing for users.

Flash messages: as mentioned above, I have provided my own German translations in our project. But when I enable/disable 2FA in the FE, the flash message text is always in English ("Your changes have been saved successfully."), even if I'm in the German FE (and a German translation for key "setup.update.success.body" exists). Something seems to go wrong with the language service in the SetupController I guess? (That's why I classified this issue as a bug.)

**Comment by codeFareith** [comment]
Could you pls provide information about your environment?
- Operating System + Version (e.g. **macOS Catalina v10.15.5**)
- Webserver Type + Version (e.g. **nginx v1.18.0**)
- PHP Type + Version (e.g. **PHP CGI v7.1**)
- TYPO3 CMS Version (e.g. **TYPO3 CMS v8.7.37**)

Thank you

**Comment by stoppeye** [comment]
So far, I've only tested this on our old development server. The specs for this are:
Windows Server 2012 R2
IIS 8.5
PHP FastCGI Version 7.2.16
TYPO3 CMS 9.5.18

(Note: I've been developing multiple multilingual TYPO3 extensions on this system and have so far never encountered this kind of problem myself.)

If I get to it, I might try your extension on a (Linux-based) production system. I'll let you know about any tests in this regard.
