### ISSUE TITLE
GA tab does not appear in user settings

### ISSUE THREAD

**Issue by LimeUwe** [codeFareith/cf_google_authenticator#16]
GA config tab appears in be_users for for admins and can be used.
My problem is, that it does not show up in user settings. This is needed if non-admin users want to configure the GA login.

I can see that there is a TCA Override in sys_template.php, which does not have any effect.

(TYPO3 8.7.24)

**Comment by codeFareith** [comment]
Isn't that something you'd configure via "ACL"?
I'll check this and if it's a bug, it'll be fixed in 1.1.4 😊

**Comment by LimeUwe** [comment]
I checked ACLs with to other people. Which one controls the tabs and field within the user settings? All I can see there is to allow access to the the user settings in gerenal, but no exclude fields or anything else.

**Comment by codeFareith** [comment]
Never mind. I found the bug and will provide a fix asap.

**Comment by LimeUwe** [comment]
Great! Thank you for the work and the great extension!
