### ISSUE TITLE
Enable for both, frontend- and backend accounts.

### ISSUE THREAD

**Issue by typo3ua** [codeFareith/cf_google_authenticator#2]
I see in README
'Enable Google 2FA (two factor authentication) for both, frontend- and backend accounts.'
... but then I see it:
'Unfortunately, de-/activating 2FA for frontend users is not implemented yet.'
...where is correct?

**Comment by codeFareith** [comment]
You're right, that's a little misleading - I'll fix that with the next commit.

To answer your question:
The foundation for de-/activating the 2FA for frontend users is given - but currently only possible via the backend.

So, if you open the overview of frontend users in the backend and select a user for editing, you will already find everything necessary under the tab Google Authenticator - so same procedure as it is for backend users.

What is still missing is the possibility to set up the 2FA via the frontend.

**Comment by codeFareith** [comment]
I just pushed release v1.0.4, which now gives the possibility to set up the 2FA via the frontend.

**Comment by typo3ua** [comment]
Yes! Is pretty cool ... Thanks!
