### ISSUE TITLE
Backend User Module: Error

### ISSUE THREAD

**Issue by woodyc79** [codeFareith/cf_google_authenticator#7]
Hello!

I've just installed your extension from EM (TYPO3 8.7.15) and when accessing the backend user module and EDIT one of the users, I get this error message: 
`Return value of CodeFareith\CfGoogleAuthenticator\Hook\UserSettings::initializeTemplateView() must be an instance of TYPO3\CMS\Fluid\View\StandaloneView, none returned`

Also if i add a return $templateView; to method initializeTemplateView, i get no QR Code in the Backend View!

Kind regards,
Christian

**Comment by codeFareith** [comment]
Hey Christian,
thank you very much for your support and reporting this bug.
Since this makes an important part of the backend unusable, the ticket will be treated with a correspondingly high priority. I'll fix it as soon as I can.

Many greetings from Germany,
Robin.

**Comment by codeFareith** [comment]
Hey again,
just want to let you know that I fixed the reported bug.
In a few minutes you should be able to download the update via EM.
