### ISSUE TITLE
save settings - cast Error - 

### ISSUE THREAD

**Issue by pfaffenrodt** [codeFareith/cf_google_authenticator#72]
# Bug report

## Prerequisites
- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Description:
If I want to enable two factor auth. I receive an cast exception. 

```
TypeError
Return value of CodeFareith\CfGoogleAuthenticator\Handler\GoogleAuthenticatorSetupHandler::hasUserEnabledAuthenticator() must be of the type boolean, integer returned
```

## Steps to reproduce:
1. Go to Backend User modul
2. Got to Google Authenticator tab
3. Click on Enable Google Authenticator
4. Click on Save
5. See error

## Expected results:
User settings saved new state. 

## Actual results:
exception thrown

## Environment

 | | |
 ---- | ----
**Platform** |  Windows
**Browser** | Google Chrome 76.0.3809.132
**Additional Context** | typo3 9.5.9
**PHP** | 7.2.20

**Comment by sascha-schieferdecker** [comment]
I can confirm this issue
