### ISSUE TITLE
strict_types produce error

### ISSUE THREAD

**Issue by pfaffenrodt** [codeFareith/cf_google_authenticator#73]
# Bug report

## Prerequisites
- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Description:
cache produce error.
strict_types should be removed from ext_localconf.php

Fatal error: strict_types declaration must be the very first statement in the script in /var/www/html/var/cache/code/cache_core/ext_localconf_9f9d6f92c02010d691198254786d5dfe61eff9c1.php on line 1847

**Comment by sascha-schieferdecker** [comment]
Furthermore the same problem exists in ext_tables.php

**Comment by xperseguers** [comment]
@codeFareith I'm a bit unsure about possible problems with the usage namespace import (`use`) in `ext_tables.php`, `ext_localconf.php`. I'm quite sure it's highly discouraged and could lead to problems once more than one extension author chooses to not follow the TYPO3 coding guidelines. However this is unrelated to this ticket and from what I see, this ticket is to be closed.

**Comment by codeFareith** [comment]
You're absolutely right, I'm going to fix this asap
