### ISSUE TITLE
Saving not working

### ISSUE THREAD

**Issue by pfaffenrodt** [codeFareith/cf_google_authenticator#74]
# Bug report

## Prerequisites

- [ x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Description:
Enabling google authenticator not working

## Steps to reproduce:
1. Go to User settings
2. Click on Enable Google Authenticator
3. Click on Save
4. reopen user settings
5. google authenticator is disabled

## Expected results:
two factor is enabled

## Actual results:
two factor still disabled

## Environment

typo3 9.5.9

**Comment by sascha-schieferdecker** [comment]
I can confirm this issue
