### ISSUE TITLE
Conflict using ig_ldap_sso_auth ext

### ISSUE THREAD

**Issue by ABartelt** [codeFareith/cf_google_authenticator#9]
**Second factor ignored with ig_ldap_sso_auth ext**
Hey,
actual i'm using [ig_ldap_sso_auth ](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth) ext for LDAP authentification in combination with active directory.
It seems like the second factor is ignored in frontend login when using the LDAP / SSO and google authenticator service.
Do you may know a solution that both services in the authentification chain could be consulted?

**Comment by codeFareith** [comment]
Hey Arne,
thanks for your issue report.
I will download the extension (ig_ldap_sso_auth) and check it. Please give me a little time, I will get back to you :)

**Comment by codeFareith** [comment]
New version is up, please check again. Thank you.

**Comment by codeFareith** [comment]
Ah okay, yeah that might be the problem!
Would you like to open a pull request with your changes so I can merge them? :)
